### ISSUE TITLE
As a consumer I want the user reviews to display like they do in the admin

### ISSUE THREAD

**Issue by sminke** [autorivalry/ar-render#23]

**Comment by sminke** [comment]
@jordanskole

**Comment by jordanskole** [comment]
@sminke @motstuff take a look at how this looks on the following pages and let me know what you think. Everything is deployed on the web for your demo, but I am not closing this ticket out so I can continue to work on it. 
- http://render.autorivalry.com/v1/matchups/-K6faTutivaLfVqSf3y6
- http://render.autorivalry.com/v1/matchups/-K8MPHsSICalBQBsHYli

**Comment by sminke** [comment]
@jordanskole this looks fantastic!  one thing i tried but couldn't figure out... in the first example you provided (http://render.autorivalry.com/v1/matchups/-K6faTutivaLfVqSf3y6) there is a "professional reviews" tab.  In the second example you provided (http://render.autorivalry.com/v1/matchups/-K8MPHsSICalBQBsHYli), the '16 Accord vs '16 Fusion comparison that I built yesterday, I couldn't find a way to get the "professional reviews" tab included.  Any idea what I need to do in the admin to make it show on the render?  Other than that, I think we are ready to present the '16 accord vs '16 fusion render in this meeting!  Thanks again for all of your hard work!

**Comment by jordanskole** [comment]
@sminke yeah, good question. 

Not every vehicle style (trim) includes reviews/ratings from Edmunds.com, so for that matchup it was showing a blank tab. I added a check to ensure that there was in fact edmunds reviews available, and that they had been selected to be included in admin. 

Inside admin under ratings there is a paragraph that describes this, but you can see the list of vehicles here: http://www.edmunds.com/new-car-ratings/

For the '16 Accord the "Touring V6 Sedan (3.5L V6 6-Speed Automatic)" style includes the edmunds.com write-up. http://www.edmunds.com/honda/accord/2016/sedan/rating/

**Comment by motstuff** [comment]
@jordanskole @sminke Great job Jordan!  I like that this option is available now in the admin to opt in/out of the edmunds reviews.  Any opportunity to left column adjust the paragraph (in bold) under the picture in (http://render.autorivalry.com/v1/matchups/-K8MPHsSICalBQBsHYli) .  The paragraph starts with "The Ford Fusion is a relatively new entrant...."

**Comment by jordanskole** [comment]
Hey @motstuff fyi, that would be a separate issue unrelated to the one about consumer reviews.
