### ISSUE TITLE
As a consumer I want the render to display in correct format

### ISSUE THREAD

**Issue by sminke** [autorivalry/ar-render#24]
(gray screen to match blue screen)

**Comment by sminke** [comment]
@jordanskole

**Comment by jordanskole** [comment]
Closing this issue because from my perspective it appears to be a duplicate of #20. If it isn't feel free to reopen it with more descriptive context. 

Also, FYI nitpicking, consumers (or anyone) doesn't really have a concept of "correct" or "incorrect."
