### ISSUE TITLE
As a consumer, I want to see more normal spacing between paragraphs and images on the render's "head to head comparisons"

### ISSUE THREAD

**Issue by sminke** [autorivalry/ar-render#32]
Current spacing in the render looks odd (some spaces too big, some too small)

**Comment by sminke** [comment]
@jordanskole when I add issues, do you always want me to tag you like I am doing here?

**Comment by jordanskole** [comment]
@sminke no you don't have to I see them all. But please try and use a screenshot for super-specific issues like these.

**Comment by jordanskole** [comment]
- screenshot from admin - [Imgur](http://i.imgur.com/93iwuXc.png)
- screenshot from render - [Imgur](http://i.imgur.com/HjgWeZD.png)

**Comment by jordanskole** [comment]
Just an fyi @sminke I will look into this for research, but I am probably not going to work on it. It doesn't make sense for me to spend `x` number of hours fixing this, instead of working on issue [ar-admin #96](https://waffle.io/autorivalry/ar-admin/cards/56a24e6d4494d27a000bf35e)

**Comment by motstuff** [comment]
@jordanskole since this will be client facing, I would encourage you to re-prioritize higher unless ar-admin#96 will fix this issue, and you don't want it #32 hanging as a duplicate

**Comment by jordanskole** [comment]
@motstuff admin#96 will make this issue moot.

**Comment by jordanskole** [comment]
Closing this issue based on our conversation on Tuesday, in terms of [ar-render #41](https://waffle.io/autorivalry/ar-render/cards/56b3e2776bd82b190007b9d6)
