### ISSUE TITLE
As an internal stakeholder, I would request the option to share my matchups with other internal stakholders

### ISSUE THREAD

**Issue by motstuff** [autorivalry/ar-render#34]
reduce duplication

**Comment by jordanskole** [comment]
@motstuff  :+1: great idea greg (although it probably belongs more to admin), this would look like a single company account and several individual personal accounts have access to the company account. Is that what you are meaning?

So we would have an omni account and all three of us, plus 7 people from omni have access?

**Comment by motstuff** [comment]
Yes!  A master account, or our current login's allowing us to access the library of all the matchups

**Comment by jordanskole** [comment]
Yeah completely agree. This is two issues to me. 
1. Auto Rivalry Staff gets "superadmin" privileges, "superadmins" can edit any matchup (easy, first issue)
2. Client "business" accounts. One business has many accounts belong to it. (larger issue, they can share logins until we get this done).

**Comment by motstuff** [comment]
@jordanskole cool, remind me do I need to move this to completed, and create two new issues, or can I clone this one to create the second issue?

**Comment by motstuff** [comment]
@sminke can you show me how you were able to add the 'admin' as a selection in waffle.io?

**Comment by motstuff** [comment]
@jordanskole Can you remove this or move it to done, and I will add this to the 'admin' issues
