### ISSUE TITLE
as a AR owner, I want to make sure we adhere to Edmunds TOS

### ISSUE THREAD

**Issue by jordanskole** [autorivalry/ar-render#35]
Review [ratings & reviews](http://developer.edmunds.com/api-documentation/vehicle/content_ratings_and_reviews/v2/), and make sure that everything complies with Edmunds TOS.

**Comment by sminke** [comment]
@jordanskole safe to assume we need this done before we go live with any clients?  Let me know if you think there is a timeline, with hard dates, available..  thanks!

**Comment by jordanskole** [comment]
@sminke correct, this should be NBD though, it is minor adjustments.
